version: "3.8"

services:
  nostr-relay:
    image: xdamman/nostr-rs-relay:latest
    container_name: nostr-relay
    restart: always
    environment:
      - DATABASE_URL=sqlite:///data/nostr.db  # Use PostgreSQL or SQLite
    volumes:
      - ./config.toml:/app/config.toml  # Mount from Git repo
      - ./favicon.ico:/app/favicon.ico  # Mount from Git repo
      - ./data:/data
    ports:
      - "8081:8081"  # Exposes relay on port 8081
    platform: linux/arm64  # Force ARM64 support if needed
